# nginx proxy address - http://172.17.0.1:8109

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - filebrowser
    ports:
      - "8109:8109"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/filebrowser:/config
      - ./rootfs/data/filebrowser:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8109"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  filebrowser:
    external: false
